### ISSUE TITLE
Speed up for large datasets?

### ISSUE THREAD

**Issue by Foztarz** [aroneklund/beeswarm#6]
I love this plot style, but I've recently started working with large datasets (10e5–10e6 elements) and noticed that the whole process becomes painfully slow as compared to ```stripchart()```, for example. Might it be possible to develop a fast version for large datasets, using ```data.table``` or something similar?

Thanks!
James

**Comment by aroneklund** [comment]
Sorry for my slow response! It's probably possible, but I don't know when I'll have a chance to look into it. I suspect it would help to write the point layout algorithm (the hidden function `.calculateSwarm`) in C or Fortran.  I am open to help or other suggestions!

**Comment by Foztarz** [comment]
Thanks for getting back to me and pointing me in the direction of ```.calculateSwarm``` . Looking at it I don't see anything obvious, except possibly that ```out``` could be a ```data.table``` rather than ```data.frame``` (the time-savings for big datasets are fantastic). Wish I had the skills to rewrite it in C or Fortran, but when I'm next working on one of these datasets I can do some benchmarking replacing steps with functions from [data.table](https://rdatatable.gitlab.io/data.table/) and ```parallel``` and see if anything helps.

**Comment by raredd** [comment]
Some thoughts:

user side

1. this only applies to `method = 'swarm'`, the others are pretty quick in my tests even for 1e6 rows, although personally I do not like that the other methods shift the data points, so I stick with swarm
2. I'm not sure how useful it is to plot that many points anyway
3. the bottleneck could be your graphics device (test with `do.plot = FALSE` to see how much speed you gain when not sending to a device). The rstudio device is very slow if that is what you are using--you could make some gains if you send the plot to `pdf` or better yet a raster image like `png` which will also be easier on your computer to view/manipulate

package side

1. it seems you would not need to [check _every_ point](https://github.com/aroneklund/beeswarm/blob/master/R/beeswarm.R#L372). If you had a rule such that only if (x[2] - x[1]) < delta, then check for overlap; otherwise, `next` this iteration.
2. c/fortran would be great

**Comment by jtrim-ons** [comment]
I'd be interested in attempting to help with a C or C++ implementation, although my availability is a bit unpredictable these days so please don't wait for me!

I'd be keen to hear others' thoughts on which language would be best to use. I've [had a go](https://github.com/jtrim-ons/beeswarm/blob/cpp/src/beeswarm.cpp) today at using Rcpp to implement the compactswarm layout I've been working on (#9 is a discussion of my R implementation of the same algorithm). Rcpp seems really nice to work with, but I don't know if there are concerns about portability of C++ etc?

The C++ version definitely gives a big speedup over R. There are other tweaks to the algorithm along the lines suggested by @raredd that could probably help too, and wouldn't be hard to implement in C, C++, or Fortran. But perhaps a simple and correct implementation is the way to go.

@aroneklund and others, I'd welcome thoughts, particularly around (1) choice of language (2) whether using a non-R language is worth the trouble (3) whether I should have a go at this or leave it to someone with more experience!

**Comment by aroneklund** [comment]
Wow, it's great that you've actually done this!  Something like this has been on my to-do list for a very long time. :)

My understanding is that the Rcpp dependency could present a bit of a barrier on platforms without a C++ compiler etc. available by default (MacOS, Windows). For this reason, I do think a C or Fortran implementation (which could be pre-compiled for these platforms) would be better, especially since the code is relatively simple. However, I don't have any experience with writing R code in anything except R -- so please correct me if I'm wrong.

If you have the time/motivation to see this through, I would definitely appreciate the contribution! And, of course, I would be happy to add your name to the author list.

I am very curious - how much of a speedup do you see with your Rcpp code?

**Comment by jtrim-ons** [comment]
I'll try to do a C version within the next month.

The C++ version makes a surprising difference. I think it's about a 100x speedup for compactswarm with 5000 points plotted. I'll try to get post some timings here later. I imagine that it would be easy to get at least an order of magnitude improvement for the swarm layout.

**Comment by Foztarz** [comment]
Sounds fantastic. I can only reiterate how useful any kind of speed-up would be for people working with large datasets hoping to plot them in swarm format.

**Comment by jtrim-ons** [comment]
So, I got a bit obsessed with writing a C implementation this week :-) I've submitted a PR, but I'd be happy to make changes.

A few timings from interactive use on my laptop:

```R
> r <- rnorm(10000)
> system.time(beeswarm(r, cex=.3))
   user  system elapsed 
  0.656   0.013   0.672 
> system.time(beeswarm(r, cex=.3, fast=FALSE))
   user  system elapsed 
 10.092   2.563  12.657 
> system.time(beeswarm(r, cex=.3, method="compactswarm"))
   user  system elapsed 
  0.973   0.044   1.018 
> system.time(beeswarm(r, cex=.3, method="compactswarm", fast=FALSE))
   user  system elapsed 
 80.930  37.270 118.265 
```

For this one instance, the C version of swarm is 15 time faster than the R version, and the C version of compactswarm is 83 times better than the R version. From my experience, the C versions of swarm and compactswarm typically give roughly one and two orders of magnitude speedups over R, respectively.

I think that the C versions could be made even faster with some extra work, but I'm hoping that the current, simple versions should be fast enough for most use cases?

I have tried to make the C versions give exactly the same results as the R versions, and I've added some tests to check this.

**Comment by jtrim-ons** [comment]
I've written an even faster version of method="swarm" at https://github.com/jtrim-ons/beeswarm/tree/faster-c-version. It passes the tests and can handle about a million points in a minute if you use an appropriate value of `cex`. But I would recommend going for the version in the pull request; it's simpler and I'm more confident that it's correct.

(A quick note on how the faster version works, assuming that the x axis is the data axis: It keeps points sorted by x value so it can quickly find points that are horizontally near to the point that is about to be placed. It then sorts these nearby points by y value; this means that the overlap check only has to look at points that have a similar y value to the candidate y.)
